name = "absurdly-rational-editor-api"
main = "src/worker.js"
compatibility_date = "2026-08-19"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "4750074"

[vars]
ALLOWED_ORIGIN = "https://absurdlyrational.com"
